# Dockerfile.postgres (not needed if using official image in docker-compose)
# FROM postgres:16
#
# ENV POSTGRES_USER=postgres_user
# ENV POSTGRES_PASSWORD='2@4p>y@nUTS$qr"'
# ENV POSTGRES_DB=postgres
#
# ENV POSTGRES_INITDB_ARGS="--encoding=UTF8 --locale=C.UTF-8"
#
# EXPOSE 5432
