version: '3.8'

services:
  streamlit:
    build:
      context: .
      dockerfile: dockerfile.streamlit
    container_name: streamlit_app
    environment:
      POSTGRES_USER: "postgres_user" # set this to your Coolify Postgres user
      POSTGRES_PASSWORD: "strong^&ss!23" # set this to your Coolify Postgres password
      POSTGRES_DB: "postgres" # set this to your Coolify Postgres database name
      POSTGRES_HOST: "bg08gs8occ0ggw40o44cc4kc" # set this to your Coolify Postgres host (domain or internal address)
      POSTGRES_PORT: 5432 # set this to your Coolify Postgres port (usually 5432)
    ports:
      - "8501:8501"
