version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres-1
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: docker.streamlit
    container_name: streamlit-app
    environment:
      DB_HOST: postgres-1
      DB_PORT: 5432
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASS: mypassword
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pg_data:
