version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypa&&word
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: dockerfile.streamlit
    container_name: streamlit-app
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pg_data:
